<?xml version="1.0"?>
<robot name="marid" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="is_ignition" default="true"/>

  <!-- Include Gazebo parameters-->
  <xacro:include filename="$(find marid_description)/urdf/marid_gazebo.xacro"/>

  <!-- ROS2 Control Library-->
  <xacro:include filename="$(find marid_description)/urdf/marid_ros2_control.xacro"/>


  <!-- Axis translation along y - adjust this value as needed -->
  <xacro:property name="axis_offset_y" value="0.1"/>
  
  <!-- Joint origins at the desired rotation axis location -->
  <xacro:property name="left_wing_xyz" value="0.0 ${0.18 + axis_offset_y} -0.04"/>
  <xacro:property name="left_wing_rpy" value="0.0 0.0 0.0"/>
  <xacro:property name="right_wing_xyz" value="0.0 ${0.18 + axis_offset_y} -0.04"/>
  <xacro:property name="right_wing_rpy" value="0.0 0.0 0.0"/>
  
  <!-- Offset for wing geometry relative to joint (to keep wing in original position) -->
  <xacro:property name="left_wing_offset" value="0.0 ${-axis_offset_y} 0.0"/>
  <xacro:property name="right_wing_offset" value="0.0 ${-axis_offset_y} 0.0"/>
  
  <xacro:property name="wing_axis" value="1 0 0"/>
  

  <link name="base_link_front">  
    <inertial>
      <mass value="3.0903248"/> 
      <origin xyz="0 0 0" rpy="0 0 0"/>  <!-- Fixed: COM at geometric center for stability -->
      <inertia ixx="0.1110930358" ixy="0.0" ixz="0.0" iyy="0.0247075659" iyz="0.0" izz="0.1288539854"/>  <!-- Fixed: Zeroed iyz to eliminate cross-coupling moments -->
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/base_link_front.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/base_link_front.stl"/>
      </geometry>
    </collision>
  </link>


  <link name="main_tail">
    <inertial>
      <mass value="0.69082118"/> 
      <origin xyz="0 0.1 0.02" rpy="0 0 0"/>
      <inertia ixx="0.0077116401" ixy="0.0" ixz="0.0" iyy="0.0006628288" iyz="0.0" izz="0.0077111242"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/main_tail.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/main_tail.stl"/>
      </geometry>
    </collision>
  </link>



  <joint name="main_tail_joint" type="fixed">
    <parent link="base_link_front"/>
    <child link="main_tail"/>
    <origin xyz="0 -.2115 -0.0555" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0" effort="1000" velocity="1000"/>
  </joint>

  
  <link name="left_wing">
    <inertial>
      <origin xyz="${left_wing_offset}" rpy="0 0 0"/>
      <mass value="1.44"/>
      <inertia ixx="0.0139618379" ixy="-0.0200668863" ixz="0.003481534" iyy="0.0399031726" iyz="0.001971806" izz="0.0531650164"/>
    </inertial>
    <visual>
      <origin xyz="${left_wing_offset}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/left_wing.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="${left_wing_offset}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/left_wing.stl"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="left_wing_joint" type="revolute">
    <parent link="base_link_front"/>
    <child link="left_wing"/>
    <origin xyz="${left_wing_xyz}" rpy="${left_wing_rpy}"/>
    <axis xyz="${wing_axis}"/>
    <dynamics damping="10" friction="5"/>
    <sensor name="left_wing_ft" type="force_torque">
      <update_rate>1</update_rate>
      <force_torque>
        <frame>child</frame>
        <measure_direction>child_to_parent</measure_direction>
      </force_torque>
      <topic>/marid/left_wing/wrench</topic>
    </sensor>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>
  
  <link name="right_wing">
    <inertial>
      <origin xyz="${right_wing_offset}" rpy="0 0 0"/>
      <mass value="1.44"/>
      <inertia ixx="0.0139618379" ixy="0.0200668863" ixz="-0.003481534" iyy="0.0399031726" iyz="0.001971806" izz="0.0531650164"/>
    </inertial>
    <visual>
      <origin xyz="${right_wing_offset}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/right_wing.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="${right_wing_offset}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/right_wing.stl"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="right_wing_joint" type="revolute">
    <parent link="base_link_front"/>
    <child link="right_wing"/>
    <origin xyz="${right_wing_xyz}" rpy="${right_wing_rpy}"/>
    <axis xyz="${wing_axis}"/>
    <dynamics damping="10" friction="5"/>
    <sensor name="right_wing_ft" type="force_torque">
      <update_rate>1</update_rate>
      <force_torque>
        <frame>child</frame>
        <measure_direction>child_to_parent</measure_direction>
      </force_torque>
      <topic>/marid/right_wing/wrench</topic>
    </sensor>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>


  <link name="tail_left">
    <inertial>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <mass value="0.1664684"/>
      <inertia ixx="0.00053436" ixy="0.0" ixz="-0.0003467078" iyy="0.000704515" iyz="0.0" izz="0.0006567504"/>
    </inertial>
    <visual>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/tail_left.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/tail_left.stl"/>
      </geometry>
    </collision>
  </link>

  <joint name="tail_left_joint" type="revolute">
    <parent link="main_tail"/>
    <child link="tail_left"/>
    <origin xyz="0 -.28 0" rpy="0 0 0"/>
    <axis xyz="0.7071 0 -0.7071"/>
    <dynamics damping="10" friction="5"/>
    <sensor name="left_tail_ft" type="force_torque">
      <update_rate>1</update_rate>
      <force_torque>
        <frame>child</frame>
        <measure_direction>child_to_parent</measure_direction>
      </force_torque>
      <topic>/marid/left_tail/wrench</topic>
    </sensor>
    <limit lower="-.524" upper=".524" effort="10" velocity="1.0"/>
  </joint>


  <link name="tail_right">
    <inertial>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <mass value="0.1664684"/>
      <inertia ixx="0.00053436" ixy="0.0" ixz="0.0003467078" iyy="0.000704515" iyz="0.0" izz="0.0006567504"/>
    </inertial>
    <visual>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/tail_right.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0.25 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://marid_description/meshes/tail_right.stl"/>
      </geometry>
    </collision>
  </link>

  <joint name="tail_right_joint" type="revolute">
    <parent link="main_tail"/>
    <child link="tail_right"/>
    <origin xyz="0 -0.28 0" rpy="0 0 0"/>
    <axis xyz="0.7071 0 0.7071"/>
    <dynamics damping="10" friction="5"/>
    <sensor name="right_tail_ft" type="force_torque">
      <update_rate>1</update_rate>
      <force_torque>
        <frame>child</frame>
        <measure_direction>child_to_parent</measure_direction>
      </force_torque>
      <topic>/marid/right_tail/wrench</topic>
    </sensor>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>


  

  <link name="imu_link">
    <inertial>
      <origin xyz="-0.00552433659106688 0.000168210391520346 0.000514000497342681" rpy="0 0 0" />
      <mass value="0.000528415362211671" />
      <inertia ixx="1.46176048428261E-08" ixy="1.40015117949421E-10" ixz="-1.99633872937403E-12"
               iyy="8.59662482954888E-09" iyz="7.52375112767959E-12"
               izz="2.30279421279312E-08" />
    </inertial>
    <visual>
        <origin xyz="0 0.05 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.01" radius="0.01"/></geometry>
    </visual>
    <collision>
        <origin xyz="0 0.1 0.02" rpy="0 0 0"/>
        <geometry><cylinder length="0.01" radius="0.01"/></geometry>
    </collision>
  </link>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0.0698986241758014" rpy="0 0 0" />
    <parent link="base_link_front" />
    <child link="imu_link" />
    <axis xyz="0 0 0" />
  </joint>

  <link name="gps_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-6" iyy="1e-6" izz="1e-6" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="gps_green">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
      </visual>
  </link>

  <joint name="gps_joint" type="fixed">
    <parent link="base_link_front"/>
    <child link="gps_link"/>
    <!-- Mount GPS on top of fuselage, behind IMU -->
    <origin xyz="0 0.05 0.08" rpy="0 0 0"/>
  </joint>

  <link name="pitot_link">
    <inertial>
      <mass value="0.005"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-7" iyy="1e-7" izz="1e-7" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="pitot_joint" type="fixed">
    <parent link="base_link_front"/>
    <child link="pitot_link"/>
    <!-- Mount on nose for clean airflow -->
    <origin xyz="0 0.4 0" rpy="0 0 0"/>
  </joint>

  <link name="baro_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-6" iyy="1e-6" izz="1e-6" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="baro_joint" type="fixed">
    <parent link="base_link_front"/>
    <child link="baro_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/> 
  </joint>


  <link name="thruster_L">
    <inertial>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <mass value="0.05"/>
      
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/><geometry><cylinder length="0.1" radius="0.015"/></geometry>
        <material name="red_thruster">
          <color rgba="1.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision><origin xyz="0 0 0"/><geometry><cylinder length="0.1" radius="0.015"/></geometry></collision>
  </link>

  <link name="thruster_R">
    <inertial>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
      </inertial>
      <visual><origin xyz="0 0 0" rpy="1.5708 0 0"/><geometry><cylinder length="0.1" radius="0.015"/></geometry>
        <material name="blue_thruster">
          <color rgba="0.0 0.0 1.0 1.0"/>
        </material>
      </visual>
      <collision><origin xyz="0 0 0"/><geometry><cylinder length="0.1" radius="0.015"/></geometry></collision>
  </link>

  <joint name="thruster_L_joint" type="revolute">
    <parent link="base_link_front"/>
    <child  link="thruster_L"/>
    <origin xyz="-0.15 0.0 -0.02" rpy="0 0 0"/>  <!-- Fixed: Moved closer to COM to reduce moments -->
    <axis xyz="0 1 0"/>  <!-- Reverted: Original axis was correct -->
    <limit lower="-3.14159" upper="3.14159" effort="100" velocity="100"/>
    <dynamics damping="0.01" friction="0.0"/>
  </joint>

  <joint name="thruster_R_joint" type="revolute">
    <parent link="base_link_front"/>
    <child  link="thruster_R"/>
    <origin xyz="0.15 0.0 -0.02" rpy="0 0 0"/>  <!-- Fixed: Moved closer to COM to reduce moments -->
    <axis xyz="0 1 0"/>  <!-- Reverted: Original axis was correct -->
    <limit lower="-3.14159" upper="3.14159" effort="100" velocity="100"/>
    <dynamics damping="0.01" friction="0.0"/>
  </joint>

  <!-- Center Thruster (for single-thruster testing) -->
  <link name="thruster_center">
    <inertial>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry><cylinder length="0.1" radius="0.015"/></geometry>
      <material name="green_thruster">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision><origin xyz="0 0 0" rpy="1.5708 0 0"/><geometry><cylinder length="0.1" radius="0.015"/></geometry></collision>
  </link>

  <joint name="thruster_center_joint" type="revolute">
    <parent link="base_link_front"/>
    <child link="thruster_center"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>  <!-- At COM - no moments -->
    <axis xyz="0 1 0"/>
    <limit lower="-3.14159" upper="3.14159" effort="100" velocity="100"/>
    <dynamics damping="0.01" friction="0.0"/>
  </joint>

</robot>